"""create phase5 security and audit tables

Revision ID: 26bd9014162f
Revises: b3113cfceea3
Create Date: 2026-09-07 04:16:15.564931

"""
from typing import Sequence, Union

# pyrefly: ignore
# type: ignore
from alembic import op
# pyrefly: ignore
# type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bd9014162f'
down_revision: Union[str, None] = 'b3113cfceea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique audit event UUID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='Username, service number, or subject identifier'),
    sa.Column('user_role', sa.String(length=30), nullable=True, comment='Authorized role at event time: COMMANDER, MEDICAL_OFFICER, PERSONNEL, SYSTEM'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed: LOGIN_SUCCESS, DATA_EXPORT, ALERT_ACKNOWLEDGE, etc.'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Resource type affected: PERSONNEL, ALERT, EXPORT, AUTH'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='Identifier of target entity'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client network IP address'),
    sa.Column('details', sa.Text(), nullable=True, comment='Structured context or JSON payload with sensitive PII scrubbed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when event occurred in UTC'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_role'), 'audit_logs', ['user_role'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique user UUID or identifier'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique login username or official service number'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt password hash'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='COMMANDER, MEDICAL_OFFICER, PERSONNEL'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='Official display name and military rank'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of most recent successful authentication'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_status', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_user_role'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
