"""create_phase2_tables

Revision ID: 830190dadd77
Revises: 
Create Date: 2026-09-07 03:09:09.964392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830190dadd77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_number', sa.String(length=50), nullable=False, comment='Unique military service identifier (e.g. SX-10492)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Synthetic personnel display name'),
    sa.Column('rank', sa.String(length=50), nullable=False, comment='Military rank (e.g., Sepoy, Havildar, Subedar, Captain)'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Corps or operational specialty (e.g., Infantry, Signals, Medical)'),
    sa.Column('unit', sa.String(length=100), nullable=False, comment='Assigned battalion or regiment'),
    sa.Column('joining_date', sa.Date(), nullable=False, comment='Date of commission or enlistment'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='ACTIVE, ON_LEAVE, DEPLOYED, HOSPITALISED, INACTIVE'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='Synthetic official contact email'),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True, comment='Emergency contact identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_rank'), 'personnel', ['rank'], unique=False)
    op.create_index(op.f('ix_personnel_role'), 'personnel', ['role'], unique=False)
    op.create_index(op.f('ix_personnel_service_number'), 'personnel', ['service_number'], unique=True)
    op.create_index(op.f('ix_personnel_status'), 'personnel', ['status'], unique=False)
    op.create_index('ix_personnel_status_unit', 'personnel', ['status', 'unit'], unique=False)
    op.create_index(op.f('ix_personnel_unit'), 'personnel', ['unit'], unique=False)
    op.create_index('ix_personnel_unit_rank', 'personnel', ['unit', 'rank'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False, comment='Theatre or post location (e.g. Siachen, Kupwara, Thar)'),
    sa.Column('deployment_type', sa.String(length=50), nullable=False, comment='HIGH_ALTITUDE, COUNTER_INSURGENCY, BORDER_OUTPOST, PEACE_STATION'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Deployment start date'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Deployment conclusion date (null if currently active)'),
    sa.Column('operational_intensity', sa.String(length=30), nullable=False, comment='LOW, MODERATE, HIGH, EXTREME'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='ACTIVE, COMPLETED, TERMINATED'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Terrain/operational context and observations'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_deployment_type'), 'deployments', ['deployment_type'], unique=False)
    op.create_index(op.f('ix_deployments_location'), 'deployments', ['location'], unique=False)
    op.create_index('ix_deployments_personnel_dates', 'deployments', ['personnel_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_deployments_personnel_id'), 'deployments', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index('ix_deployments_status_type', 'deployments', ['status', 'deployment_type'], unique=False)
    op.create_table('duty_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('duty_date', sa.Date(), nullable=False, comment='Date duty was performed'),
    sa.Column('duty_type', sa.String(length=50), nullable=False, comment='SENTRY, COMBAT_PATROL, CONVOY_ESCORT, NIGHT_GUARD, ADMINISTRATIVE'),
    sa.Column('hours_worked', sa.Float(), nullable=False, comment='Total hours on duty within 24-hour cycle (0.0 to 24.0)'),
    sa.Column('night_duty', sa.Boolean(), nullable=False, comment='Flag indicating shift included night hours (22:00-06:00)'),
    sa.Column('consecutive_duty_days', sa.Integer(), nullable=False, comment='Consecutive active duty days without a 24h rest period'),
    sa.Column('workload_score', sa.Float(), nullable=False, comment='Subjective/calculated duty intensity rating (1.0 to 10.0)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duty_logs_duty_date'), 'duty_logs', ['duty_date'], unique=False)
    op.create_index('ix_duty_logs_night_consecutive', 'duty_logs', ['night_duty', 'consecutive_duty_days'], unique=False)
    op.create_index('ix_duty_logs_personnel_date', 'duty_logs', ['personnel_id', 'duty_date'], unique=False)
    op.create_index(op.f('ix_duty_logs_personnel_id'), 'duty_logs', ['personnel_id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False, comment='ANNUAL, CASUAL, COMPASSIONATE, MEDICAL'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date of requested leave'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End date of requested leave'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='Total inclusive leave days'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='PENDING, APPROVED, REJECTED, COMPLETED, CANCELLED'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Stated reason or welfare context'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_records_personnel_dates', 'leave_records', ['personnel_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_leave_records_personnel_id'), 'leave_records', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_leave_records_status'), 'leave_records', ['status'], unique=False)
    op.create_index('ix_leave_records_status_type', 'leave_records', ['status', 'leave_type'], unique=False)
    op.create_table('wellness_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.Date(), nullable=False, comment='Date assessment was submitted'),
    sa.Column('stress_score', sa.Float(), nullable=False, comment='Perceived stress level (0.0=No stress, 10.0=Severe crisis)'),
    sa.Column('sleep_quality_score', sa.Float(), nullable=False, comment='Sleep quality rating (0.0=Insomnia/Disrupted, 10.0=Optimal rest)'),
    sa.Column('fatigue_score', sa.Float(), nullable=False, comment='Exhaustion rating (0.0=Fully energized, 10.0=Chronic exhaustion)'),
    sa.Column('wellbeing_score', sa.Float(), nullable=False, comment='General morale and welfare score (0.0=Distress, 10.0=Thriving)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Confidential counselor or individual remarks'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wellness_surveys_personnel_date', 'wellness_surveys', ['personnel_id', 'survey_date'], unique=False)
    op.create_index(op.f('ix_wellness_surveys_personnel_id'), 'wellness_surveys', ['personnel_id'], unique=False)
    op.create_index('ix_wellness_surveys_stress_fatigue', 'wellness_surveys', ['stress_score', 'fatigue_score'], unique=False)
    op.create_index(op.f('ix_wellness_surveys_survey_date'), 'wellness_surveys', ['survey_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_surveys_survey_date'), table_name='wellness_surveys')
    op.drop_index('ix_wellness_surveys_stress_fatigue', table_name='wellness_surveys')
    op.drop_index(op.f('ix_wellness_surveys_personnel_id'), table_name='wellness_surveys')
    op.drop_index('ix_wellness_surveys_personnel_date', table_name='wellness_surveys')
    op.drop_table('wellness_surveys')
    op.drop_index('ix_leave_records_status_type', table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_status'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_personnel_id'), table_name='leave_records')
    op.drop_index('ix_leave_records_personnel_dates', table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_duty_logs_personnel_id'), table_name='duty_logs')
    op.drop_index('ix_duty_logs_personnel_date', table_name='duty_logs')
    op.drop_index('ix_duty_logs_night_consecutive', table_name='duty_logs')
    op.drop_index(op.f('ix_duty_logs_duty_date'), table_name='duty_logs')
    op.drop_table('duty_logs')
    op.drop_index('ix_deployments_status_type', table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_personnel_id'), table_name='deployments')
    op.drop_index('ix_deployments_personnel_dates', table_name='deployments')
    op.drop_index(op.f('ix_deployments_location'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployment_type'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('ix_personnel_unit_rank', table_name='personnel')
    op.drop_index(op.f('ix_personnel_unit'), table_name='personnel')
    op.drop_index('ix_personnel_status_unit', table_name='personnel')
    op.drop_index(op.f('ix_personnel_status'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_service_number'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_role'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_rank'), table_name='personnel')
    op.drop_table('personnel')
    # ### end Alembic commands ###
