"""create phase4 alert tables

Revision ID: b3113cfceea3
Revises: 830190dadd77
Create Date: 2026-09-07 03:51:40.385434

"""
from typing import Sequence, Union

# pyrefly: ignore
# type: ignore
from alembic import op
# pyrefly: ignore
# type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3113cfceea3'
down_revision: Union[str, None] = '830190dadd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Calculated stress risk score at time of alert creation [0.0 - 1.0]'),
    sa.Column('risk_category', sa.String(length=30), nullable=False, comment='HIGH or CRITICAL'),
    sa.Column('trigger_type', sa.String(length=50), nullable=False, comment='DUTY_OVERLOAD, HARDSHIP_DEPLOYMENT, LEAVE_DEPRIVATION, CLINICAL_SURVEY_DISTRESS, COMPOSITE_ML_RISK'),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Short summary of the welfare alert'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed breakdown of the contributing operational stressors'),
    sa.Column('severity', sa.String(length=30), nullable=False, comment='HIGH or CRITICAL'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='NEW, ACKNOWLEDGED, IN_REVIEW, RESOLVED, DISMISSED'),
    sa.Column('recommended_action', sa.Text(), nullable=True, comment='Recommended mitigation intervention (R&R, shift rotation, clinical referral)'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Audit remarks recording the specific actions taken upon resolution'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True, comment='Username or service number of authorizing officer who resolved the alert'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when alert was resolved or dismissed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_personnel_id'), 'alerts', ['personnel_id'], unique=False)
    op.create_index('ix_alerts_personnel_status', 'alerts', ['personnel_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index('ix_alerts_personnel_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_personnel_id'), table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
